### ISSUE TITLE
[trivy-operator v0.21.0 update issue] timed out waiting for cache to be synced, v1alpha1.RbacAssessmentReport

### ISSUE THREAD

**Issue by cp319391** [aquasecurity/helm-charts#9]
What steps did you take and what happened:
while updating the trivy-operator to v0.21.0 from v0.20.6

Our trivy-operator is restarting every 2 - 3minutes. It exits with the following error message:
`error: unable to run trivy operator: starting controllers manager: [failed to wait for rbacassessmentreport caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.RbacAssessmentReport, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]`

What did you expect to happen:
Pod runs stable.

Trivy-Operator version: v0.21.0

Environment:

Trivy-Operator version (use trivy-operator version): v0.21.0

**Comment by jcortejoso** [comment]
I'm seeing the same in multiple clusters we run trivy-operator.

**Comment by chen-keinan** [comment]
@jcortejoso @cp319391 can you please try deleting all `rbacassessmentreport` from all resources and restart, no worries report will automatically created

@cp319391  Can you please re-open `trivy-operator` issue and close this one

**Comment by cp319391** [comment]
reopened under trivy-operator.
